<div style="border:1px solid #2A6991;border-radius: 20px; height:300px;overflow-y: auto;width:710px;overflow-x: hidden;">
Privacy Statement

        Recruitment Software Solution Corp. Pte. Ltd. 200802289H  (hereafter referred to as “we”) takes the privacy 
        of personal information of the users of Talent Atlas (hereafter referred to as “TA” or “this website”) 
        very seriously, and we handle it with utmost care.

        TA has agreed to inform you about:

        The collection and use of your personally identifiable information
        How and why the information gathered from users is used, and conditions of sharing and disclosure of 
        personal information to third parties
        Your opt-out rights
        The security measures implemented to protect personal data from leaking, crash, defacing, loss, 
        and unauthorized use
        How you can change and update your personal information
        How we train our employees to protect personal information
        Our compliance with legal regulations on the protection of personal data
        How we review privacy policy, privacy statement, and compliance program to protect your personal information
        If you feel that we do not abide by this privacy statement please contact us at info@talentatlas.com

        Personal information collected from you by our company

        1. Collection and use of personally identifiable information
        We are the sole owner of all information collected on this website. We do not sell, share, or lease this 
        personal information to third parties in any other ways than stated in this privacy statement.

        (1) Personally identifiable information collected on this website
        In order to apply for jobs, or receive scout emails or email updates about the latest job advertisements,
        or to post job advertisements, you must first you must first apply to a posting on
        the website’s (http://www.talentatlas.com) job listing page.   When applying, you are required to give your 
        contact details or resume. After the initial application, you can register your resume in our resume database.
        When you register your resume, you are required to give us your contact information and career summary.

        The above information is used for registering and publicizing your resume to companies registered with us,
        and for applying for jobs with those companies, or for the purpose of advertising your positions to jobseekers.
        The username (ID) and password are used to confirm your identity when accessing or changing the information 
        you registered. It is also used to contact you about site updates. When you register with this website,
        you will be asked questions with regard to privacy settings.

        To disclose your resume, so that the company you are applying for can see your information.
        To disclose your resume so that companies seeking people with your profile can contact you.

        (2) Cookies
        A cookie is a text file that is placed on a website user’s computer and contains information that the user 
        left on that website. We are using cookies generated by the TA website and third party services on this 
        website to manage your access history. You may choose to modify your browser settings to accept or decline cookies.
        Please understand that if you choose to decline cookies you will not be able to register your resume or apply for jobs.

        (3) Log files
        On this website, we save the information of users who accessed the site into in the form of an access log, and 
        use it for the analysis of statistics related to the use of the website. The access log includes the IP address 
        from which our website was accessed, the number of accesses, and the page views, but it does not include any 
        personally identifiable information. The information is not used for any other purposes, and we do not disclose
        the access log in principle.

        (4) Web Beacons
        We are using Web Beacons generated by third party services to track the outcome of member registration. 
        Any information gathered by the use of Web Beacons will not be identifiable.

        (5) Verification of how we use the personal information we collect and store
        If we change this privacy statement, we will publicize these changes on our website.
        You can always verify what kind of information we collect, and how we use this information.

        Our company stores the following personal information:

        Name
        Gender
        Date of birth
        Address
        Telephone number
        Email address
        Educational and professional background
        Language skills (English, Japanese)
        Current salary
        Nationality, visa status
        Username, ID number, password


        2. How and why the information gathered from users is used, and about sharing of information and disclosing
        information to third parties
        (1) Use within the scope of purposes
        Our companies’ fundamental principle is to not use your registered information for any other purposes than 
        the ones given below. We use the information in accordance with the privacy statement that was in place when 
        the information was collected.

        To register and publicize your resume to companies registered with us, and to apply for jobs with those companies.
        However, users themselves decide on, and set, the privacy settings of the resume.

        For statistical purposes on user demographics and use of the Resume Bank
        To verify your identity when accessing or modifying previously registered information
        To contact you about site updates and the latest job postings
        To disclose your personal information to companies using TA.

        (2) Sharing of personal information
        Our company partners with other companies to provide you with special services. In the case that you choose 
        to sign up with any of those services, we will as necessary share your name and other contact details with 
        the company that provides that service. We do not permit our partners to use your personal information for 
        any other purposes than provision of the said services.


        (3) Passing on personal information to third parties
        We will not disclose or pass on the information you register on our website to third parties without your consent. 
        The only exceptions are the cases stated below.

        When based upon a law, ordinance, or general principle
        When ordered by governmental or regulatory authorities
        When passing on the information is deemed necessary to protect a person’s life, body, or property from threat,
        or to protect the legitimate rights and business interests of our companies or others, or when it is impossible 
        to acquire your consent.
        There may be cases when our company has to deposit personal information with a third party in order to 
        subcontract business. In such a case, we will investigate the third party company according to a pre-set 
        standard, conclude the necessary contract, and take all legally necessary measures.

        (4) Links to other sites
        This website contains links to other sites. Please understand that we cannot take responsibility for the 
        privacy practices of such other websites. We ask you to read the privacy statement when using this website.
        This privacy statement applies only to information collected on this website.

        3. Your right to refuse (“Opt-out”)
        (1) In the case a third party collects your personal information
        If a third party other than our company collects your personal information, we will certainly inform you about it.
        In such a case, you may choose whether or not you would like to continue receiving the service from an outside provider.

        (2) Change in purpose of use of personal data
        If we use your personal data in any other way than stated at the time of collection of said data,
        we inform you by email or telephone. Without your consent in this case, we will not use your personal data 
        in any different way than stated in our company’s purpose of data use.

        4. Security measures implemented to protect your personal data from leaking, crash, defacing, loss,
        and unauthorized use .This website has implemented all precautionary measures to protect your data. 
        When you submit important information to this website, your information will be protected both online and offline.

        To protect critical information online, we have put in place a firewall, encrypted transmission, hacking detector, virus scan, and port blocking.
        We are sparing no efforts to also protect our users’ information offline, and we have implemented high-level internal security measures as well.
        Not only critical information, but all information we collect from our users, is limited for use only within our company.

        (1) Server administration
        We have set up a firewall so that no third party can access our server.
        Our web server and email server are set up in a data center, but managed by our own staff.
        The server where our company keeps personal data is administered in a safe environment, in a locked cage,
        which can be entered only upon authentication by photo ID and vein authentication.

        If you have any questions about the security measures on our website, please contact us 
        by email at info@talentatlas.com.

        (2) Email
        We protect our email server and individual terminals from infection with viruses by installing anti-virus software.

        (3) SSL encryption
        When you enter your personal information in the registration process, we use the industry-wide 
        security standard SSL (Secure Socket Layer) to encrypt your data and prevent them from interception 
        while they are transmitted over the internet.

        (4) Access rights within our company
        Only those employees are permitted access to the personal information users enter on this website
        who need them for fulfilling special duties.
        Apart from the above, it may be necessary to permit access to your personal information within the scope of our operations.

        5. Accessing and changing your personal information
        Regarding requests for display, modification, addition, or deletion of your personal data, or discontinuance
        of use: based on the below contents, you can have that done by sending us an email at the email address provided 
        in (3) below.

        (1) Displaying, changing, deleting your personal data or withdrawal from membership
        Our company deals properly with users’ requests regarding display, change, or deletion of data, or withdrawal 
        from membership within the limits of reason. You can also change your personal data yourself, by logging in
        with your ID and password. If you have a request, please contact us by email at the below address given in (3).

        (2) Inquiries and claims about your personal information
        If users contact us with inquiries or claims regarding their personal information, we will properly address 
        such requests within the scope of reason. For inquiries, please contact us by email at the below address given in (3).

        (3) Contact for (1) and (2) above
        We have set up a special support desk to address user inquiries named in (1) and (2) above.

        Customer Support Desk
        Recruitment Software Solution Corp. Pte. Ltd. 200802289H
        Email: info@talentatlas.com

        (4) Change in correspondence procedures
        If there is a change in the communication procedures stated above, we will inform you about that change.　
        Such announcements will be made on this website, or by email from our company.

        6. Training of employees on the protection of personal information
        We constantly keep our employees informed about the latest developments in security and privacy issues.
        At least once every year, and whenever a new privacy statement comes in place, we conduct trainings for all employees.
        Our employees are obliged to do their utmost to protect the privacy of our users’ and customers’ personal information.
        When employees leave their desks, we have password-protected screen savers in place.

        7. Compliance with legal regulations on the protection of personal information
        Our company complies with legal regulations on the protection of personal information.


        8. Review of privacy policy and privacy statement to protect personal information
        (1) Responsibility for review
        Based on the statement of audit and other factors such as the business environment, our company’s president
        reviews the privacy policy and privacy statement as well as the terms of use regularly to ensure the best possible protection of personal information.

        (2) Convocation of review meeting
        When the president sees grounds for a review as below, he will within a considerable amount of time convoke a meeting (hereafter “review meeting”) 
        to review privacy policy, privacy statement, and terms of use.

        When the auditor submits an audit report to the president.
        When the administrator in charge of protecting personal information or the person in charge of protecting personal information ask for a review of 
        contents or text of the privacy policy or privacy statement.
        In any other cases when the president deems a review necessary.

        (3) Audit
        Our company conducts audits about the protection of personal information. Subject to the audit are all systems, operations, and departments handling personal data.

        (4) Timing of the audit
        The timing of audits is as follows:

        An operations audit is conducted at least once a year, in regular intervals
        On a timely basis together with revisions of the privacy policy, privacy statement, or terms of use
        At other times whenever necessary
</div>